// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoq1T6yVOp_49B1eU2mXgII1rzE8Dsxj0',
    appId: '1:973748496987:web:0ff8d37f59181703eb6d7e',
    messagingSenderId: '973748496987',
    projectId: 'project123-4b734',
    authDomain: 'project123-4b734.firebaseapp.com',
    databaseURL: 'https://project123-4b734-default-rtdb.firebaseio.com',
    storageBucket: 'project123-4b734.appspot.com',
    measurementId: 'G-E2TYL0LKD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUrixOZjOJOyVrFRX5aAaO4DtEll7PE8Q',
    appId: '1:973748496987:android:daa6a7b4c6a6342ceb6d7e',
    messagingSenderId: '973748496987',
    projectId: 'project123-4b734',
    databaseURL: 'https://project123-4b734-default-rtdb.firebaseio.com',
    storageBucket: 'project123-4b734.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqIzA4PNCRYw6RN2xhpPp91pNmgcewEHI',
    appId: '1:973748496987:ios:186994cef287d062eb6d7e',
    messagingSenderId: '973748496987',
    projectId: 'project123-4b734',
    databaseURL: 'https://project123-4b734-default-rtdb.firebaseio.com',
    storageBucket: 'project123-4b734.appspot.com',
    androidClientId: '973748496987-savume6f7hcoc3v7agedot7g9datd2n7.apps.googleusercontent.com',
    iosClientId: '973748496987-1rjo9ut3upgjf8gol5m2noq4068mcr7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.LifeLines',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqIzA4PNCRYw6RN2xhpPp91pNmgcewEHI',
    appId: '1:973748496987:ios:186994cef287d062eb6d7e',
    messagingSenderId: '973748496987',
    projectId: 'project123-4b734',
    databaseURL: 'https://project123-4b734-default-rtdb.firebaseio.com',
    storageBucket: 'project123-4b734.appspot.com',
    androidClientId: '973748496987-savume6f7hcoc3v7agedot7g9datd2n7.apps.googleusercontent.com',
    iosClientId: '973748496987-1rjo9ut3upgjf8gol5m2noq4068mcr7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.LifeLines',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoq1T6yVOp_49B1eU2mXgII1rzE8Dsxj0',
    appId: '1:973748496987:web:6cfda4e2ed80f253eb6d7e',
    messagingSenderId: '973748496987',
    projectId: 'project123-4b734',
    authDomain: 'project123-4b734.firebaseapp.com',
    databaseURL: 'https://project123-4b734-default-rtdb.firebaseio.com',
    storageBucket: 'project123-4b734.appspot.com',
    measurementId: 'G-7NWBVLRCV8',
  );

}